### ISSUE TITLE
[Mod Request] Farm & Charm + Compats

### ISSUE THREAD

**Issue by xR4YM0ND** [Pandaismyname1/Let-s-Do-EMI-Compat#2]
Hey there satisfy just released Lets Do Farm & Charm + 3 Compat mods 

Could you add a seperate version for these or switch to these entirely pls

Need that EMI integration in the Aged Modpack 

~ Thank you for your work!

**Comment by Pandaismyname1** [comment]
On vac right now, will start dev in 2 weeks

**Comment by xR4YM0ND** [comment]
Awesome, good times

**Comment by Pandaismyname1** [comment]
A new update that adds compat with Farm & Charm just rolled out, you can find it on CurseForge & Modrinth.
